// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/user/repository.go

package mocks

import (
	models "cre-resume-backend/internal/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return _m.recorder
}

// GetUserByEmail mocks base method
func (_m *MockUserRepositoryInterface) GetUserByEmail(email string) (*models.User, error) {
	ret := _m.ctrl.Call(_m, "GetUserByEmail", email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail
func (_mr *MockUserRepositoryInterfaceMockRecorder) GetUserByEmail(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetUserByEmail), arg0)
}

// CreateUser mocks base method
func (_m *MockUserRepositoryInterface) CreateUser(user *models.User) error {
	ret := _m.ctrl.Call(_m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser
func (_mr *MockUserRepositoryInterfaceMockRecorder) CreateUser(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CreateUser), arg0)
}

// Activation mocks base method
func (_m *MockUserRepositoryInterface) Activation(userID string) error {
	ret := _m.ctrl.Call(_m, "Activation", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activation indicates an expected call of Activation
func (_mr *MockUserRepositoryInterfaceMockRecorder) Activation(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Activation", reflect.TypeOf((*MockUserRepositoryInterface)(nil).Activation), arg0)
}
