// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/cv/model.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// MockCVModelInterface is a mock of CVModelInterface interface
type MockCVModelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCVModelInterfaceMockRecorder
}

// MockCVModelInterfaceMockRecorder is the mock recorder for MockCVModelInterface
type MockCVModelInterfaceMockRecorder struct {
	mock *MockCVModelInterface
}

// NewMockCVModelInterface creates a new mock instance
func NewMockCVModelInterface(ctrl *gomock.Controller) *MockCVModelInterface {
	mock := &MockCVModelInterface{ctrl: ctrl}
	mock.recorder = &MockCVModelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockCVModelInterface) EXPECT() *MockCVModelInterfaceMockRecorder {
	return _m.recorder
}
