// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/user/service.go

package mocks

import (
	models "cre-resume-backend/internal/user/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserServiceInterface is a mock of UserServiceInterface interface
type MockUserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceInterfaceMockRecorder
}

// MockUserServiceInterfaceMockRecorder is the mock recorder for MockUserServiceInterface
type MockUserServiceInterfaceMockRecorder struct {
	mock *MockUserServiceInterface
}

// NewMockUserServiceInterface creates a new mock instance
func NewMockUserServiceInterface(ctrl *gomock.Controller) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockUserServiceInterface) EXPECT() *MockUserServiceInterfaceMockRecorder {
	return _m.recorder
}

// Register mocks base method
func (_m *MockUserServiceInterface) Register(register *models.User) error {
	ret := _m.ctrl.Call(_m, "Register", register)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register
func (_mr *MockUserServiceInterfaceMockRecorder) Register(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Register", reflect.TypeOf((*MockUserServiceInterface)(nil).Register), arg0)
}
