// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/user/view.go

package mocks

import (
	models "cre-resume-backend/internal/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUserViewInterface is a mock of UserViewInterface interface
type MockUserViewInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserViewInterfaceMockRecorder
}

// MockUserViewInterfaceMockRecorder is the mock recorder for MockUserViewInterface
type MockUserViewInterfaceMockRecorder struct {
	mock *MockUserViewInterface
}

// NewMockUserViewInterface creates a new mock instance
func NewMockUserViewInterface(ctrl *gomock.Controller) *MockUserViewInterface {
	mock := &MockUserViewInterface{ctrl: ctrl}
	mock.recorder = &MockUserViewInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockUserViewInterface) EXPECT() *MockUserViewInterfaceMockRecorder {
	return _m.recorder
}

// Register mocks base method
func (_m *MockUserViewInterface) Register(register *models.User) error {
	ret := _m.ctrl.Call(_m, "Register", register)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register
func (_mr *MockUserViewInterfaceMockRecorder) Register(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Register", reflect.TypeOf((*MockUserViewInterface)(nil).Register), arg0)
}

// Login mocks base method
func (_m *MockUserViewInterface) Login(login *models.Login, loginType string) (*string, error) {
	ret := _m.ctrl.Call(_m, "Login", login, loginType)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login
func (_mr *MockUserViewInterfaceMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Login", reflect.TypeOf((*MockUserViewInterface)(nil).Login), arg0, arg1)
}

// ActivateUser mocks base method
func (_m *MockUserViewInterface) ActivateUser(userID string) error {
	ret := _m.ctrl.Call(_m, "ActivateUser", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser
func (_mr *MockUserViewInterfaceMockRecorder) ActivateUser(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ActivateUser", reflect.TypeOf((*MockUserViewInterface)(nil).ActivateUser), arg0)
}

// ReSend mocks base method
func (_m *MockUserViewInterface) ReSend(email string) error {
	ret := _m.ctrl.Call(_m, "ReSend", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReSend indicates an expected call of ReSend
func (_mr *MockUserViewInterfaceMockRecorder) ReSend(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ReSend", reflect.TypeOf((*MockUserViewInterface)(nil).ReSend), arg0)
}
